"""create barber table

Revision ID: 8131ea9f90ea
Revises: 
Create Date: 2021-12-21 13:09:38.921780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8131ea9f90ea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
	# ### commands auto generated by Alembic - please adjust! ###
	op.create_table('barber',
	sa.Column('id', sa.Integer(), nullable=False, autoincrement=True),
	sa.Column('name', sa.String(length=250), nullable=False),
	sa.Column('document', sa.String(length=20), nullable=False, unique=True),
	sa.Column('phone', sa.String(length=20), nullable=True),
	sa.Column('create_at', sa.Date()),
	sa.Column('update_at', sa.Date()),
	sa.PrimaryKeyConstraint('id')
	)
	# ### end Alembic commands ###


def downgrade():
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_table('barber')
	# ### end Alembic commands ###
