"""create payment model and schema

Revision ID: 9c22a4e4627b
Revises: 4854916c17fb
Create Date: 2022-01-04 12:19:56.975244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c22a4e4627b'
down_revision = '4854916c17fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False, autoincrement=True),
    sa.Column('barber_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), default=sa.func.now()),
    sa.Column('updated_at', sa.DateTime(), default=sa.func.now(), onupdate=sa.func.now()),
    sa.ForeignKeyConstraint(['barber_id'], ['barber.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment')
    # ### end Alembic commands ###
