"""reformated pyment model

Revision ID: fb4668e886c6
Revises: 9c22a4e4627b
Create Date: 2022-01-04 13:39:05.568297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb4668e886c6'
down_revision = '9c22a4e4627b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('total_payment', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment', 'total_payment')
    # ### end Alembic commands ###
